direction: right
vars: {
  d2-config: {
    pad: 0
    theme-id: 200
    layout-engine: elk
    theme-overrides: {
      N1: "#ffffff"
      N7: "#191919"
      B1: "#ffffff"
    }
  }
}

grid-columns: 3
grid-gap: 50

**.style.border-radius: 8
**.style.font-size: 35
(** <- scriptDef.*)[*].style.stroke-width: 4

plugin-l1: Plugin
plugin-l2: Plugin
plugin-l3: Plugin

core: Core {
  width: 200
  height: 400
}

plugin-r4: Plugin
plugin-r5: Plugin
plugin-r6: Plugin

plugin* -> core
