direction: right
vars: {
  d2-config: {
    pad: 0
    theme-id: 200
    layout-engine: elk
    theme-overrides: {
      N1: "#ffffff"
      N7: "#191919"
      B1: "#ffffff"
    }
  }
}

**.style.border-radius: 8
**.style.font-size: 35
(** <- scriptDef.*)[*].style.stroke-width: 4

host: Scripting Host (app) {
  grid-columns: 2
  compiler: Compiler
  evaluator: Evaluator
}

scriptDef: Script Definition {
  near: top-center
  compilation: Compilation configuration
  host: Host configuration
  evaluation: Evaluation configuration
}

host.compiler <- scriptDef.compilation
host.evaluator <- scriptDef.evaluation
host <- scriptDef.host

(scriptDef.* -> **)[*].style.stroke-width: 40
