direction: right
vars: {
  d2-config: {
    pad: 0
    theme-id: 200
    layout-engine: elk
    theme-overrides: {
      N1: "#ffffff"
      N7: "#191919"
      B1: "#ffffff"
    }
  }
}

**.style.font-size: 35
(** -> **)[*].style.stroke-width: 4

bytecode: JVM Classes {
  near: bottom-center
}

host: Scripting Host (app) {
  grid-columns: 2
  compiler: Compiler
  evaluator: Evaluator
}

script: Script {
  near: center-left
  shape: page
}

script -> host.compiler: {
  style.animated: true
}
host.compiler -> bytecode: {
  style.animated: true
}
bytecode -> host.evaluator: {
  style.animated: true
}

output: Result {
  near: center-right
  #   grid-columns: 1
  #   stdout
  #   "Runtime Objects"
}
host.evaluator -> output: {
  style.animated: true
}

scriptDef: Script Definition {
  near: top-center
  #   compilation: Compilation configuration
  #   host: Host configuration
  #   evaluation: Evaluation configuration
}

host.compiler <- scriptDef
host.evaluator <- scriptDef
host <- scriptDef
script <- scriptDef
output <- scriptDef

(* -> *)[*].style.stroke-width: 10
