stages:
  - build
  - deploy
build:
  stage: build
  image:
    name: alpine:latest
  script:
    - echo 'Hello World from build'
deploy-dev-0:
  stage: deploy
  image:
    name: alpine:latest
  needs:
    - build
  script:
    - echo Deployed dev-0
deploy-dev-1:
  stage: deploy
  image:
    name: alpine:latest
  needs:
    - build
  script:
    - echo Deployed dev-1
deploy-dev-2:
  stage: deploy
  image:
    name: alpine:latest
  needs:
    - build
  script:
    - echo Deployed dev-2
