name: Build and Deploy Openconf
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ openconf ]
jobs:
  jbang:
    runs-on: ubuntu-latest
    name: A job to run jbang
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      
    environment:
      name: netlify
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{secrets.TOKEN}}
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - name: jbang
      uses: jbangdev/jbang-action@v0.114.0
      with:
        script: revealkt@limebeck.dev
        scriptargs: bundle ./presentation/kotlin-script.reveal.kts
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './out'
        production-branch: openconf
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.OPENCONF_NETLIFY_SITE_ID }}
      timeout-minutes: 1
